### ISSUE TITLE
Stop using deprecated `set-output`

### ISSUE THREAD

**Issue by atoomic** [perl-actions/install-with-cpm#15]
Need to adjust `set-output` usage, this is currently throwing that warning 

> The `set-output` command is deprecated and will be disabled soon. 
> Please upgrade to using Environment Files. 
> For more information see: 
> https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by atoomic** [comment]
Let's try to update the full upstream stack via #16

**Comment by atoomic** [comment]
This is already reported upstream and tracked via https://github.com/actions/toolkit/issues/1218

Temporary Suggestion:
```js
const os = require("os")
const fs = require("fs")

function setOutput(key, value) {
  // Temporary hack until core actions library catches up with github new recommendations
  const output = process.env['GITHUB_OUTPUT']
  fs.appendFileSync(output, `${key}=${value}${os.EOL}`)
}
```

Probably better to wait for a fix from upstream

**Comment by JJ** [comment]
This should be fixed already upstream, right?

**Comment by atoomic** [comment]
this is not fixed upstream view https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L199

```js
export function setOutput(name: string, value: any): void {
  const filePath = process.env['GITHUB_OUTPUT'] || ''
  if (filePath) {
    return issueFileCommand('OUTPUT', prepareKeyValueMessage(name, value))
  }

  process.stdout.write(os.EOL)
  issueCommand('set-output', {name}, toCommandValue(value))
}
```

**Comment by atoomic** [comment]
there is a case to fix it we should track https://github.com/actions/toolkit/issues/1336

**Comment by rafork** [comment]
This is getting urgent. Two weeks left (maybe?):

From https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Starting today [October 11, 2022] runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout. We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

**Comment by atoomic** [comment]
probably consider using `console.log` instead

**Comment by atoomic** [comment]
this should now be fixed by 798bfcd40dc7945e0a91b34da0aff715a8aa59ca
